FROM node:20-alpine AS build
WORKDIR /app

# Copy all frontend files and install dependencies
COPY . .
RUN npm ci && npm run build

# Serve the production build with 'serve'
FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve

COPY --from=build /app/dist /app/build
EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]
