---
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ./start.sh
    volumes:
      - ./backend:/app
      - ./frontend/certs:/app/certs
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
